// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdmuphNEtHSc52zHPUyNTSnTR_gzN2Sn4',
    appId: '1:608111615365:web:18363cc76ecc1a566a78ec',
    messagingSenderId: '608111615365',
    projectId: 'rsvp-rally',
    authDomain: 'rsvp-rally.firebaseapp.com',
    storageBucket: 'rsvp-rally.appspot.com',
    measurementId: 'G-6KSHXXC27D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDugugKqA6OF0nsjLRAD7uoBHs_JF4VPiU',
    appId: '1:608111615365:android:6d8d156e14100c396a78ec',
    messagingSenderId: '608111615365',
    projectId: 'rsvp-rally',
    storageBucket: 'rsvp-rally.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcH4nWOWuEhBES8iF6lw8oWV9EitjFkoo',
    appId: '1:608111615365:ios:338ae1804fc7f1ba6a78ec',
    messagingSenderId: '608111615365',
    projectId: 'rsvp-rally',
    storageBucket: 'rsvp-rally.appspot.com',
    iosBundleId: 'com.example.rsvpRally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcH4nWOWuEhBES8iF6lw8oWV9EitjFkoo',
    appId: '1:608111615365:ios:b5c92e2404cfb3db6a78ec',
    messagingSenderId: '608111615365',
    projectId: 'rsvp-rally',
    storageBucket: 'rsvp-rally.appspot.com',
    iosBundleId: 'com.example.rsvpRally.RunnerTests',
  );
}
